// Goods Return Analysis — data model, loading, filtering and aggregations.
// Source: the uploaded QA Excel, kept in localStorage. There is no bundled fallback —
// no upload history means a blank dashboard, which is what getQaRaw() returns.
// (generated by scripts/qa-extract.mjs from the two QA Excel files).
import * as XLSX from 'xlsx'
import { isBlankLabel, parseQaSheets, type QaSheet } from './qaSheets'
import { authHeaders } from './auth'
import { apiUrl } from './unit'

export interface SkfRow {
  date: string
  month: string // YYYY-MM
  customer: string
  item: string
  qty: number
  ok: number
  rejection: number
  challan: string
  invoice: string
}
export interface ObsRow {
  date: string
  month: string
  item: string
  received: number
  observation: string
  ok: number
  rework: number
  afterReworkOk: number
  afterReworkNok: number
}
export interface QaRaw {
  generatedAt: string
  skf: SkfRow[]
  obs: ObsRow[]
  /** Every sheet of the uploaded workbook, read generically — drives the Sheet filter. */
  sheets?: QaSheet[]
}

/** Every filter is multi-select. An EMPTY array means "no restriction" (i.e. All), which
 *  is why there is no longer an `ALL` sentinel value mixed in with real option values. */
export interface QaFilters {
  month: string[]
  year: string[]
  customer: string[]
  product: string[]
  complaintType: string[]
  observation: string[]
  status: string[]
  /** Which workbook sheet the dashboard is showing. Empty = the built-in summary. */
  sheet: string[]
}
export const EMPTY_FILTERS: QaFilters = {
  month: [],
  year: [],
  customer: [],
  product: [],
  complaintType: [],
  observation: [],
  status: [],
  sheet: [],
}
/** True when `value` passes a multi-select filter (empty selection = everything passes). */
const picked = (selected: string[], value: string) => selected.length === 0 || selected.includes(value)

const FISCAL = ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar']
const MON = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

/** A row's month is 'YYYY-MM'; rows whose Excel date could not be read carry ''. Those
 *  must stay blank — treating them as month 1 silently dumped them into January and
 *  produced a bogus "-1-00" fiscal year in the filters. */
export const monthName = (ym: string) => {
  const m = +String(ym).slice(5, 7)
  return m >= 1 && m <= 12 ? MON[m - 1] : ''
}
export function fiscalYear(ym: string): string {
  const y = +String(ym).slice(0, 4)
  const m = +String(ym).slice(5, 7)
  if (!y || m < 1 || m > 12) return '' // undated row — no fiscal year to report
  const fy = m >= 4 ? y : y - 1
  return `${fy}-${String((fy + 1) % 100).padStart(2, '0')}`
}
/** 'YYYY-MM' → 'Nov-24' for month-wise table/chart labels. */
export const monthLabel = (ym: string) => {
  const n = monthName(ym)
  return n ? `${n}-${String(ym).slice(2, 4)}` : '—'
}

/** Map a free-text inspection observation to a defect category for the Pareto view. */
export function defectCategory(observation: string): string {
  const s = observation.toLowerCase()
  if (!s) return 'Others'
  if (/(rust|surface|line ?mark|scratch|dent|corros|stain)/.test(s)) return 'Surface Defect'
  if (/(bore|\bod\b|\bid\b|face|dimension|chamfer|collar|width|taper|\+|\-|micron|oversize|undersize)/.test(s)) return 'Dimension Issue'
  if (/(heat|hardness|\bht\b|temper|soft)/.test(s)) return 'Heat Treatment'
  if (/(assembly|cage|rivet|clearance|noise|rotation)/.test(s)) return 'Assembly Issue'
  if (/(material|crack|porosity|inclusion|raw)/.test(s)) return 'Material Defect'
  if (/(pack|label|marking|packing)/.test(s)) return 'Packing Issue'
  if (/(ok|found ok|clear|accept)/.test(s)) return 'Verified OK'
  return 'Others'
}

/** Title-case + collapse case variants so "rust"/"RUST"/"Rust" merge into one bucket. */
export function canonObservation(observation: string): string {
  const s = observation.replace(/\s+/g, ' ').trim()
  if (!s) return '—'
  return s
    .toLowerCase()
    .replace(/\b([a-z])/g, (m) => m.toUpperCase())
}

// ---- uploaded-data persistence ----
const STORE_KEY = 'qa.raw.v1'
const HIST_KEY = 'qa.uploads.v1'
const API = '/api/qa'

export interface QaUploadEntry {
  id: string
  at: number // epoch ms
  kind: 'skf' | 'obs'
  label: string // human format name
  fileName: string
  rows: number
}

export interface QaStoreState {
  raw: QaRaw
  history: QaUploadEntry[]
}

export const EMPTY_RAW: QaRaw = { generatedAt: '', skf: [], obs: [] }
const EMPTY_STATE: QaStoreState = { raw: EMPTY_RAW, history: [] }

function validQaState(value: unknown): value is QaStoreState {
  if (!value || typeof value !== 'object') return false
  const state = value as Partial<QaStoreState>
  return !!state.raw && Array.isArray(state.raw.skf) && Array.isArray(state.raw.obs) && Array.isArray(state.history)
}

async function qaRequest(path: string, method = 'GET', body?: QaStoreState): Promise<unknown> {
  const response = await fetch(apiUrl(path), {
    method,
    headers: authHeaders(),
    body: body === undefined ? undefined : JSON.stringify(body),
    cache: 'no-store',
  })
  if (!response.ok) {
    let message = `QA database request failed (HTTP ${response.status}).`
    try {
      const error = (await response.json()) as { error?: unknown }
      if (typeof error.error === 'string') message = error.error
    } catch {
      // Keep the status message when the server did not return JSON.
    }
    throw new Error(message)
  }
  return response.json()
}

function readLegacyQaState(): QaStoreState | null {
  let rawText: string | null
  let historyText: string | null
  try {
    rawText = localStorage.getItem(STORE_KEY)
    historyText = localStorage.getItem(HIST_KEY)
  } catch {
    return null
  }
  if (rawText === null && historyText === null) return null

  let raw: QaRaw = EMPTY_RAW
  let history: QaUploadEntry[] = []
  try {
    if (rawText !== null) raw = JSON.parse(rawText) as QaRaw
    if (historyText !== null) history = JSON.parse(historyText) as QaUploadEntry[]
  } catch {
    throw new Error('Saved QA browser data could not be read; it has been left untouched.')
  }
  const state = { raw, history }
  if (!validQaState(state)) throw new Error('Saved QA browser data has an invalid format; it has been left untouched.')
  return state
}

function clearLegacyQaState() {
  try {
    localStorage.removeItem(STORE_KEY)
    localStorage.removeItem(HIST_KEY)
  } catch {
    // The database copy is committed; stale legacy data is no longer read.
  }
}

/** Load QA data from SQLite and merge this browser's old cache before removing it. */
export async function loadQaState(): Promise<QaStoreState> {
  const saved = await qaRequest(API)
  if (saved !== null) {
    if (!validQaState(saved)) throw new Error('The saved QA database record has an invalid format.')
  }
  const legacy = readLegacyQaState()
  if (!legacy) return saved === null ? EMPTY_STATE : saved
  const migrated = await qaRequest(`${API}/migrate`, 'POST', legacy)
  if (!validQaState(migrated)) throw new Error('The QA browser data migration returned an invalid database record.')
  clearLegacyQaState()
  return migrated
}

export async function saveQaState(state: QaStoreState): Promise<QaStoreState> {
  const saved = await qaRequest(API, 'POST', state)
  if (!validQaState(saved)) throw new Error('The QA database returned an invalid saved record.')
  clearLegacyQaState()
  return saved
}

export async function clearQaState(): Promise<void> {
  await qaRequest(API, 'DELETE')
  clearLegacyQaState()
}

/** Uploaded data drives the dashboard; no upload history means a blank dashboard. */
export async function getQaRaw(): Promise<QaRaw> {
  const state = await loadQaState()
  return state.history.length ? state.raw : EMPTY_RAW
}

export async function loadQaHistory(): Promise<QaUploadEntry[]> {
  return (await loadQaState()).history
}

// ---- browser Excel parsers (same normalisation as scripts/qa-extract.mjs) ----
type Cell = string | number | null | undefined
const numCell = (v: Cell): number => {
  if (v == null || v === '-' || v === '') return 0
  const n = typeof v === 'number' ? v : parseFloat(String(v).replace(/,/g, ''))
  return Number.isFinite(n) ? n : 0
}
const toISO = (v: Cell): string => {
  if (typeof v === 'number' && v > 20000) return new Date(Math.round((v - 25569) * 86400 * 1000)).toISOString().slice(0, 10)
  const m = String(v ?? '').match(/(\d{1,2})[.\-/](\d{1,2})[.\-/](\d{2,4})/)
  if (m) {
    const [, d, mo, y] = m
    const yr = y.length === 2 ? `20${y}` : y
    return `${yr}-${mo.padStart(2, '0')}-${d.padStart(2, '0')}`
  }
  return ''
}
const keyOf = (row: Record<string, Cell>, pred: (h: string) => boolean) =>
  Object.keys(row).find((k) => pred(k.replace(/\s+/g, ' ').trim().toLowerCase()))

const firstSheet = (buf: ArrayBuffer) => {
  const wb = XLSX.read(buf, { type: 'array' })
  const ws = wb.Sheets[wb.SheetNames[0]]
  // Some exports (e.g. with embedded images) blow the sheet range out to the full
  // XFD (16384) column width, which makes sheet_to_json iterate millions of empty
  // cells and hang the tab. Clamp to the first ~40 columns — the reports are ~14 wide.
  if (ws['!ref']) {
    const r = XLSX.utils.decode_range(ws['!ref'])
    if (r.e.c > 40) {
      r.e.c = 40
      ws['!ref'] = XLSX.utils.encode_range(r)
    }
  }
  return XLSX.utils.sheet_to_json<Record<string, Cell>>(ws, { defval: null })
}

/** Parse a "Customer Goods Return" workbook (Customer / Item / Quantity / OK / Rejection …). */
const skfRowOf = (r: Record<string, Cell>): SkfRow => {
      const kDate = keyOf(r, (h) => h.includes('received date'))
      const kMonth = keyOf(r, (h) => h === 'month')
      const kCust = keyOf(r, (h) => h.includes('customer'))
      const kItem = keyOf(r, (h) => h === 'item')
      const kQty = keyOf(r, (h) => h === 'quantity')
      const kOk = keyOf(r, (h) => h === 'ok')
      const kRej = keyOf(r, (h) => h.includes('reject'))
      const kChallan = keyOf(r, (h) => h.includes('challan no'))
      const kInv = keyOf(r, (h) => h.includes('invoice no'))
      const iso = toISO(kMonth ? r[kMonth] : null) || toISO(kDate ? r[kDate] : null)
      return {
        date: toISO(kDate ? r[kDate] : null),
        month: iso ? iso.slice(0, 7) : '',
        customer: String((kCust ? r[kCust] : '') ?? '').trim().replace(/\s+/g, ' ').toUpperCase(),
        item: String((kItem ? r[kItem] : '') ?? '').trim(),
        qty: numCell(kQty ? r[kQty] : 0),
        ok: numCell(kOk ? r[kOk] : 0),
        rejection: numCell(kRej ? r[kRej] : 0),
        challan: String((kChallan ? r[kChallan] : '') ?? '').trim(),
        invoice: String((kInv ? r[kInv] : '') ?? '').trim(),
  }
}
export function parseSkfWorkbook(buf: ArrayBuffer): SkfRow[] {
  return firstSheet(buf).map(skfRowOf).filter((r) => r.item || r.qty)
}

/** Parse an "MRS Observation Return good" workbook (Item / Received Qty / Observation / Rework …). */
const obsRowOf = (r: Record<string, Cell>): ObsRow => {
      const kDate = keyOf(r, (h) => h.includes('return date'))
      const kMonth = keyOf(r, (h) => h.includes('received month'))
      const kItem = keyOf(r, (h) => h.includes('item name'))
      const kRecv = keyOf(r, (h) => h.includes('received') && h.includes('qty'))
      const kSkfObs = keyOf(r, (h) => h.includes('skf observation'))
      const kMrsObs = keyOf(r, (h) => h.includes('mrs observation'))
      const kOk = keyOf(r, (h) => h.includes('ok') && h.includes('qty') && !h.includes('re-work') && !h.includes('rework'))
      const kRework = keyOf(r, (h) => h.includes('rework qty') || (h.includes('rework') && h.includes('qty')))
      const kArwOk = keyOf(r, (h) => h.includes('after') && h.includes('ok') && !h.includes('n-ok'))
      const kArwNok = keyOf(r, (h) => h.includes('after') && h.includes('n-ok'))
      const iso = toISO(kMonth ? r[kMonth] : null) || toISO(kDate ? r[kDate] : null)
      return {
        date: toISO(kDate ? r[kDate] : null),
        month: iso ? iso.slice(0, 7) : '',
        item: String((kItem ? r[kItem] : '') ?? '').trim(),
        received: numCell(kRecv ? r[kRecv] : 0),
        observation: String((kMrsObs ? r[kMrsObs] : kSkfObs ? r[kSkfObs] : '') ?? '').trim(),
        ok: numCell(kOk ? r[kOk] : 0),
        rework: numCell(kRework ? r[kRework] : 0),
        afterReworkOk: numCell(kArwOk ? r[kArwOk] : 0),
        afterReworkNok: numCell(kArwNok ? r[kArwNok] : 0),
  }
}
export function parseObsWorkbook(buf: ArrayBuffer): ObsRow[] {
  return firstSheet(buf).map(obsRowOf).filter((r) => r.observation || r.received)
}

/** The two Status filter buckets. */
export const STATUS_OPTIONS = ['Good Qty', 'Scrap Qty'] as const

/** Status of one return line — drives the Status filter. A line that carries ANY
 *  rejection counts as Scrap Qty; the old middle "Partial" bucket was dropped, so a line
 *  with both good and rejected pieces now lands in Scrap Qty rather than its own group. */
function skfStatus(r: SkfRow): (typeof STATUS_OPTIONS)[number] {
  return r.rejection > 0 ? 'Scrap Qty' : 'Good Qty'
}

// ---- filtering ----
export function filterSkf(rows: SkfRow[], f: QaFilters): SkfRow[] {
  return rows.filter(
    (r) =>
      picked(f.month, monthName(r.month)) &&
      picked(f.year, fiscalYear(r.month)) &&
      picked(f.customer, r.customer) &&
      picked(f.product, r.item) &&
      picked(f.status, skfStatus(r)),
  )
}
export function filterObs(rows: ObsRow[], f: QaFilters): ObsRow[] {
  return rows.filter(
    (r) =>
      picked(f.month, monthName(r.month)) &&
      picked(f.year, fiscalYear(r.month)) &&
      picked(f.product, r.item) &&
      picked(f.complaintType, defectCategory(r.observation)) &&
      picked(f.observation, canonObservation(r.observation)),
  )
}

/**
 * Read ONE workbook that holds everything: the two source sheets (found by name) plus every
 * other sheet, read generically for the Sheet filter.
 */
export function parseWorkbookAll(buf: ArrayBuffer): QaRaw {
  const wb = XLSX.read(buf, { type: 'array' })
  const find = (pred: (n: string) => boolean) => wb.SheetNames.find((n) => pred(n.toLowerCase()))
  const skfName = find((n) => n.includes('customer goods return') && !n.includes('pivot'))
  const obsName = find((n) => n.includes('observation') && !n.includes('pivot'))
  const rowsOf = (name?: string) => {
    if (!name) return []
    const ws = wb.Sheets[name]
    if (ws['!ref']) {
      const r = XLSX.utils.decode_range(ws['!ref'])
      if (r.e.c > 40) {
        r.e.c = 40
        ws['!ref'] = XLSX.utils.encode_range(r)
      }
    }
    return XLSX.utils.sheet_to_json<Record<string, Cell>>(ws, { defval: null })
  }
  return {
    generatedAt: new Date().toISOString(),
    skf: rowsOf(skfName).map(skfRowOf).filter((r) => r.item || r.customer),
    obs: rowsOf(obsName).map(obsRowOf).filter((r) => r.item || r.observation),
    sheets: parseQaSheets(buf),
  }
}

// ---- filter option lists (from the full, unfiltered dataset) ----
export function filterOptions(raw: QaRaw) {
  const uniq = (arr: string[]) => [...new Set(arr.filter(Boolean))]
  const monthsPresent = uniq([...raw.skf, ...raw.obs].map((r) => monthName(r.month)))
  return {
    month: FISCAL.filter((m) => monthsPresent.includes(m)),
    year: uniq([...raw.skf, ...raw.obs].map((r) => fiscalYear(r.month))).sort(),
    customer: uniq(raw.skf.map((r) => r.customer)).sort(),
    product: uniq([...raw.skf.map((r) => r.item), ...raw.obs.map((r) => r.item)]).sort(),
    complaintType: uniq(raw.obs.map((r) => defectCategory(r.observation))).sort(),
    observation: uniq(raw.obs.map((r) => canonObservation(r.observation))).sort(),
    status: [...STATUS_OPTIONS],
  }
}

const sum = <T,>(arr: T[], get: (t: T) => number) => arr.reduce((s, t) => s + get(t), 0)

/** A "<something> × month" quantity matrix — the shape both pivot tables render. */
export interface MonthPivot {
  months: string[] // YYYY-MM, ascending (sort keys)
  labels: string[] // Nov-24 … (display)
  rows: { name: string; cells: number[]; total: number }[] // sorted by total, desc
  colTotals: number[]
  grand: number
}

/** Roll `src` up into a name × month matrix. Only months present in `src` become columns,
 *  so a table never carries a column of dashes. Undated rows are skipped (see `undated`). */
function buildPivot<T extends { month: string }>(src: T[], nameOf: (r: T) => string, valueOf: (r: T) => number): MonthPivot {
  const months = [...new Set(src.map((r) => r.month).filter(Boolean))].sort()
  const col = new Map(months.map((m, i) => [m, i]))
  const agg = new Map<string, number[]>()
  for (const r of src) {
    const i = col.get(r.month)
    if (i === undefined) continue
    // A blank label is not a category — it is a cell nobody filled in. Counting it made an
    // "—" row that outweighed every real defect, so those rows stay out of the pivot.
    const name = nameOf(r)
    if (isBlankLabel(name)) continue
    let cells = agg.get(name)
    if (!cells) {
      cells = new Array(months.length).fill(0)
      agg.set(name, cells)
    }
    cells[i] += valueOf(r)
  }
  const rows = [...agg.entries()]
    .map(([name, cells]) => ({ name, cells, total: cells.reduce((s, n) => s + n, 0) }))
    .sort((a, b) => b.total - a.total)
  return {
    months,
    labels: months.map(monthLabel),
    rows,
    colTotals: months.map((_, i) => rows.reduce((s, r) => s + r.cells[i], 0)),
    grand: rows.reduce((s, r) => s + r.total, 0),
  }
}

/* ---------------------------------------------------------------------------
   Analysis rows for the Customer / Product / Defect tabs.

   IMPORTANT — what the two sheets can and cannot answer:
   • Customer lives ONLY in Customer Goods Return (skf). Quantities there are the
     RETURNED quantity; neither sheet carries the quantity originally supplied, so
     "return %" is always share-of-returns, never share-of-dispatch.
   • Defect / observation lives ONLY in MRS Observation (obs), which has NO customer
     column. Customer → defect is therefore an INDIRECT join through Item, and a defect
     is never split across the customers that returned the same item.
--------------------------------------------------------------------------- */

export interface CustomerRow {
  customer: string
  items: number // distinct items returned
  returns: number // challan lines
  qty: number
  ok: number
  rejection: number
  rejPct: number // rejection ÷ qty
}

export interface CustomerItemRow {
  customer: string
  item: string
  returns: number
  qty: number
  ok: number
  rejection: number
  /** Defect qty recorded against this ITEM (all customers) — see the note above. */
  defectQty: number
  topDefect: string
}

export interface ProductRow {
  item: string
  customers: number
  returns: number
  qty: number
  ok: number
  rejection: number
  incidence: number // observation lines raised for this item
  defectQty: number // received qty on those lines
  issues: number // distinct observations
  topIssue: string
  topIssueQty: number
}

export interface DefectRow {
  defect: string
  category: string
  incidence: number
  qty: number // received qty carrying this observation
  ok: number
  rework: number
  reworkOk: number
  notOk: number
  items: number
  topItem: string
}

export interface QaModel {
  skf: SkfRow[]
  obs: ObsRow[]
  kpis: {
    totalComplaints: number
    totalReturnQty: number
    totalCustomers: number
    totalProducts: number
    totalReturns: number
    good: number
    afterRework: number
    afterRejection: number
    defectPct: number
    /** Same ratio as defectPct, expressed in parts per million. */
    defectPpm: number
    avgReturnQtyPerMonth: number
  }
  /** Defect (MRS observation) × month, by received qty. */
  defectPivot: MonthPivot
  /** Item × month, by return qty. */
  itemPivot: MonthPivot
  /** Customer Analysis tab. */
  customers: CustomerRow[]
  customerItems: CustomerItemRow[]
  /** Product Analysis tab. */
  products: ProductRow[]
  /** Defect Analysis tab. */
  defects: DefectRow[]
  /** Rows the sheets couldn't date — they can't appear in any month-wise view, so they
   *  are surfaced instead of being silently mislabelled. */
  undated: { sheet: 'Customer Goods Return' | 'MRS Observation'; item: string; who: string; qty: number }[]
}

export function buildModel(raw: QaRaw, f: QaFilters): QaModel {
  const skf = filterSkf(raw.skf, f)
  let obs = filterObs(raw.obs, f)

  // The MRS Observation sheet has no customer column, so filterObs() cannot honour the
  // Customer filter. Left alone, picking one customer still showed EVERY other customer's
  // observations — items that customer never returned turned up with 0 return qty but a
  // large defect qty. Scope observations to the items that customer actually returned:
  // the same item → item join the Customer × Item tables already document.
  if (f.customer.length > 0) {
    const mine = new Set(skf.map((r) => r.item))
    obs = obs.filter((r) => mine.has(r.item))
  }

  const totalReturnQty = sum(skf, (r) => r.qty)
  const good = sum(skf, (r) => r.ok)
  const afterRejection = sum(skf, (r) => r.rejection)
  const afterRework = sum(obs, (r) => r.afterReworkOk)
  const months = new Set(skf.map((r) => r.month))
  const kpis = {
    totalComplaints: obs.length,
    totalReturnQty,
    totalCustomers: new Set(skf.map((r) => r.customer)).size,
    totalProducts: new Set([...skf.map((r) => r.item), ...obs.map((r) => r.item)]).size,
    totalReturns: skf.length,
    good,
    afterRework,
    afterRejection,
    defectPct: totalReturnQty ? (afterRejection / totalReturnQty) * 100 : 0,
    defectPpm: totalReturnQty ? (afterRejection / totalReturnQty) * 1_000_000 : 0,
    avgReturnQtyPerMonth: months.size ? totalReturnQty / months.size : 0,
  }

  // ---- the two pivot tables ----
  // Defect rows come from MRS Observation (received qty per observation); item rows come
  // from Customer Goods Return (return qty), which is what the Total Return Qty KPI sums.
  const defectPivot = buildPivot(obs, (r) => canonObservation(r.observation), (r) => r.received)
  const itemPivot = buildPivot(skf, (r) => r.item, (r) => r.qty)

  // ---- per-item defect index (drives Product + Defect tabs, and the item→defect join) ----
  type ItemDefect = { qty: number; incidence: number }
  const defectsByItem = new Map<string, Map<string, ItemDefect>>()
  for (const r of obs) {
    const item = r.item || '—'
    const d = canonObservation(r.observation)
    let inner = defectsByItem.get(item)
    if (!inner) {
      inner = new Map()
      defectsByItem.set(item, inner)
    }
    const cur = inner.get(d) || { qty: 0, incidence: 0 }
    cur.qty += r.received
    cur.incidence += 1
    inner.set(d, cur)
  }
  /** Highest-qty observation recorded against an item, '' when the item has none. */
  const topDefectOf = (item: string): { name: string; qty: number } => {
    const inner = defectsByItem.get(item)
    if (!inner || inner.size === 0) return { name: '', qty: 0 }
    let best = { name: '', qty: -1 }
    for (const [name, v] of inner) if (v.qty > best.qty) best = { name, qty: v.qty }
    return best
  }

  // ---- Customer Analysis ----
  type CAgg = { items: Set<string>; returns: number; qty: number; ok: number; rejection: number }
  const custAgg = new Map<string, CAgg>()
  type CIAgg = { returns: number; qty: number; ok: number; rejection: number }
  const custItemAgg = new Map<string, CIAgg>() // key: `customer\u0000item` — see the NUL note below
  for (const r of skf) {
    const c = r.customer || '—'
    let a = custAgg.get(c)
    if (!a) {
      a = { items: new Set(), returns: 0, qty: 0, ok: 0, rejection: 0 }
      custAgg.set(c, a)
    }
    a.items.add(r.item || '—')
    a.returns += 1
    a.qty += r.qty
    a.ok += r.ok
    a.rejection += r.rejection

    const k = `${c}\u0000${r.item || '—'}`
    const b = custItemAgg.get(k) || { returns: 0, qty: 0, ok: 0, rejection: 0 }
    b.returns += 1
    b.qty += r.qty
    b.ok += r.ok
    b.rejection += r.rejection
    custItemAgg.set(k, b)
  }
  const customers: CustomerRow[] = [...custAgg.entries()]
    .map(([customer, a]) => ({
      customer,
      items: a.items.size,
      returns: a.returns,
      qty: a.qty,
      ok: a.ok,
      rejection: a.rejection,
      rejPct: a.qty ? (a.rejection / a.qty) * 100 : 0,
    }))
    .sort((x, y) => y.qty - x.qty)
  const customerItems: CustomerItemRow[] = [...custItemAgg.entries()]
    .map(([k, v]) => {
      const [customer, item] = k.split('\u0000')
      const td = topDefectOf(item)
      const inner = defectsByItem.get(item)
      return {
        customer,
        item,
        ...v,
        defectQty: inner ? [...inner.values()].reduce((s, d) => s + d.qty, 0) : 0,
        topDefect: td.name,
      }
    })
    // Same rule as `products` — a customer/item pair with nothing returned is noise.
    .filter((r) => r.qty !== 0 || r.ok !== 0 || r.rejection !== 0)
    .sort((x, y) => y.qty - x.qty)

  // ---- Product Analysis (skf quantities + obs observations, joined on item) ----
  const itemAgg = new Map<string, { customers: Set<string>; returns: number; qty: number; ok: number; rejection: number }>()
  for (const r of skf) {
    const item = r.item || '—'
    let a = itemAgg.get(item)
    if (!a) {
      a = { customers: new Set(), returns: 0, qty: 0, ok: 0, rejection: 0 }
      itemAgg.set(item, a)
    }
    a.customers.add(r.customer || '—')
    a.returns += 1
    a.qty += r.qty
    a.ok += r.ok
    a.rejection += r.rejection
  }
  // Items seen only in the observation sheet still belong in Product Analysis.
  const allItems = new Set([...itemAgg.keys(), ...defectsByItem.keys()])
  const products: ProductRow[] = [...allItems]
    .map((item) => {
      const a = itemAgg.get(item)
      const inner = defectsByItem.get(item)
      const list = inner ? [...inner.values()] : []
      const td = topDefectOf(item)
      return {
        item,
        customers: a ? a.customers.size : 0,
        returns: a ? a.returns : 0,
        qty: a ? a.qty : 0,
        ok: a ? a.ok : 0,
        rejection: a ? a.rejection : 0,
        incidence: list.reduce((s, d) => s + d.incidence, 0),
        defectQty: list.reduce((s, d) => s + d.qty, 0),
        issues: inner ? inner.size : 0,
        topIssue: td.name,
        topIssueQty: Math.max(0, td.qty),
      }
    })
    // An item with no return, no good and no rejection was never actually returned — it
    // only exists in the observation sheet. Plotting it produced empty bars and a "0"
    // tooltip, so it is dropped from Product Analysis entirely.
    .filter((p) => p.qty !== 0 || p.ok !== 0 || p.rejection !== 0)
    .sort((x, y) => y.qty - x.qty || y.defectQty - x.defectQty)

  // ---- Defect Analysis ----
  type DAgg = { incidence: number; qty: number; ok: number; rework: number; reworkOk: number; notOk: number; items: Map<string, number> }
  const defAgg = new Map<string, DAgg>()
  for (const r of obs) {
    const d = canonObservation(r.observation)
    let a = defAgg.get(d)
    if (!a) {
      a = { incidence: 0, qty: 0, ok: 0, rework: 0, reworkOk: 0, notOk: 0, items: new Map() }
      defAgg.set(d, a)
    }
    a.incidence += 1
    a.qty += r.received
    a.ok += r.ok
    a.rework += r.rework
    a.reworkOk += r.afterReworkOk
    a.notOk += r.afterReworkNok
    const item = r.item || '—'
    a.items.set(item, (a.items.get(item) || 0) + r.received)
  }
  const defects: DefectRow[] = [...defAgg.entries()]
    .map(([defect, a]) => {
      let topItem = ''
      let best = -1
      for (const [item, q] of a.items) if (q > best) [topItem, best] = [item, q]
      return {
        defect,
        category: defectCategory(defect),
        incidence: a.incidence,
        qty: a.qty,
        ok: a.ok,
        rework: a.rework,
        reworkOk: a.reworkOk,
        notOk: a.notOk,
        items: a.items.size,
        topItem,
      }
    })
    .sort((x, y) => y.qty - x.qty)

  // Rows whose Excel date column was empty/unreadable — flagged so the sheet can be fixed.
  const undated: QaModel['undated'] = [
    ...skf.filter((r) => !monthName(r.month)).map((r) => ({ sheet: 'Customer Goods Return' as const, item: r.item || '—', who: r.customer || '—', qty: r.qty })),
    ...obs.filter((r) => !monthName(r.month)).map((r) => ({ sheet: 'MRS Observation' as const, item: r.item || '—', who: r.observation || '—', qty: r.received })),
  ]

  return { skf, obs, kpis, defectPivot, itemPivot, customers, customerItems, products, defects, undated }
}

// ---- formatting ----
export const fmtInt = (n: number) => Math.round(n).toLocaleString('en-IN')
export const fmtK = (n: number) => (Math.abs(n) >= 1000 ? `${(n / 1000).toFixed(2)}K` : fmtInt(n))
export const fmtPct = (n: number) => `${n.toFixed(2)}%`
